# Generated by Django 4.2.20 on 2025-04-09 14:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255)),
                ('file_path', models.FileField(upload_to='uploaded_files/')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('iv', models.CharField(blank=True, help_text="Vecteur d'initialisation", max_length=64, null=True)),
                ('file_hash', models.CharField(blank=True, help_text='Hash du fichier', max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, help_text='Token généré (HMAC)', max_length=256)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='files.file')),
            ],
        ),
    ]
