# Generated by Django 4.2.20 on 2025-04-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_creation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantserver',
            name='django_superuser_email',
            field=models.EmailField(blank=True, help_text='Email pour le superuser du Tenant', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tenantserver',
            name='django_superuser_password',
            field=models.CharField(blank=True, help_text='Mot de passe pour le superuser du Tenant (affiché temporairement en clair)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenantserver',
            name='django_superuser_username',
            field=models.CharField(blank=True, help_text="Nom d'utilisateur pour le superuser du Tenant", max_length=150, null=True),
        ),
    ]
