# Generated by Django 4.2.20 on 2025-04-16 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('server_creation', '0002_tenantserver_django_superuser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantserver',
            name='created_by',
            field=models.ForeignKey(help_text='Utilisateur qui a créé ce serveur Tenant', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_servers', to=settings.AUTH_USER_MODEL),
        ),
    ]
