
services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: tenant_db
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      PGPORT: 5435
    ports:
      - "5435:5435"
    volumes:
      - db_tenant:/var/lib/postgresql/data

volumes:
  db_tenant: