
services:
  master-web:
    build: .
    volumes:
      - .:/app
      - ../tenant/:/app/tenant/
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - common-network

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: master_db
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - common-network

volumes:
  postgres_data:

networks:
  common-network:
    external: true